framework:
    default_locale: en_GB
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en_GB
            - en
#        providers:
#            crowdin:
#                dsn: '%env(CROWDIN_DSN)%'
#            loco:
#                dsn: '%env(LOCO_DSN)%'
#            lokalise:
#                dsn: '%env(LOKALISE_DSN)%'
