- { code: de_DE, text: Deutsch }
- { code: en_GB, text: English }
- { code: es_ES, text: Español }
- { code: es_AR, text: Español argentino }
- { code: fr_FR, text: Français }
- { code: id_ID, text: Bahasa Indonesia }
- { code: it_IT, text: Italiana }
- { code: kv_RU, text: коми кыв }
- { code: nb_NO, text: Norsk bokmål }
- { code: nn_NO, text: Norsk nynorsk }
- { code: pl_PL, text: Język polski }
- { code: pt_BR, text: Português brasileiro }
- { code: ru_RU, text: Русский }
- { code: th_TH, text: ภาษาไทย }
- { code: tr_TR, text: Türkçe }
- { code: sl_SI, text: Slovenščina }
- { code: sv_SE, text: Svenska }
- { code: uk_UA, text: українська }
- { code: vi_VI, text: Tiếng việt }
- { code: ja_JP, text: 日本語 }
- { code: ko_KR, text: 한국어 }
- { code: zh_CN, text: 简体中文 }
- { code: zh_TW, text: 繁體中文 }
- { code: he_IL, text: עִברִית }
